Repository huru-huru/huruhuru-Server, pull requests merged in 2023-11, with the labels that each got.

#2 [CHORE] 프로젝트 세팅
  huruhuru/.gitignore
  huruhuru/build.gradle
  huruhuru/gradle/wrapper/gradle-wrapper.properties
  huruhuru/gradlew
  huruhuru/gradlew.bat
  huruhuru/settings.gradle
  huruhuru/src/main/java/com/huruhuru/huruhuru/HuruhuruApplication.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/controller/MemberController.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/domain/BaseTimeEntity.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/domain/entity/MemberEntity.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/dto/request/member/MemberSignInRequest.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/dto/response/member/MemberGetResponse.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/PropertyConfig.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/WebSecurityConfig.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/repository/MemberRepository.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/service/MemberService.java
  huruhuru/src/main/resources/application.yml
  huruhuru/src/test/java/com/huruhuru/huruhuru/HuruhuruApplicationTests.java
Labels: chore

#10 [FEAT] 로그인/회원가입/인증인가
  huruhuru/.gitignore
  huruhuru/build.gradle
  huruhuru/src/main/java/com/huruhuru/huruhuru/HuruhuruApplication.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/controller/MemberController.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/controller/QuestionController.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/domain/entity/MemberEntity.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/domain/entity/QuestionEntity.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/domain/entity/ScoreEntity.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/dto/ErrorResponse.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/dto/request/member/MemberSignInRequest.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/BCryptConfig.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/JpaAuditingConfig.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/PropertyConfig.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/SecurityConfig.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/TimezoneConfig.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/WebSecurityConfig.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/jwt/CustomJwtAuthenticationEntryPoint.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/jwt/JwtAuthenticationFilter.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/jwt/JwtTokenProvider.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/jwt/JwtValidationType.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/jwt/UserAuthentication.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/exception/GlobalExceptionHandler.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/exception/InvalidTokenException.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/repository/MemberJpaRepository.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/repository/MemberRepository.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/service/MemberService.java
  huruhuru/src/main/resources/application.yml
Labels: feature

#16 Feature/question
  .DS_Store
  .idea/.DS_Store
  huruhuru/.DS_Store
  huruhuru/build.gradle
  huruhuru/src/.DS_Store
  huruhuru/src/main/.DS_Store
  huruhuru/src/main/java/.DS_Store
  huruhuru/src/main/java/com/.DS_Store
  huruhuru/src/main/java/com/huruhuru/.DS_Store
  huruhuru/src/main/java/com/huruhuru/huruhuru/.DS_Store
  huruhuru/src/main/java/com/huruhuru/huruhuru/controller/QuestionController.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/domain/entity/QuestionEntity.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/domain/entity/ScoreEntity.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/dto/.DS_Store
  huruhuru/src/main/java/com/huruhuru/huruhuru/dto/ScoreRequest.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/.DS_Store
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/CustomUserDetail.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/repository/QuestionJpaRepository.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/repository/ScoreJpaRepository.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/service/MemberService.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/service/QuestionService.java
  huruhuru/src/main/resources/application.properties
  huruhuru/src/main/resources/application.yml
Labels: feature

#20 [FIX] 로그인/회원가입 수정사항
  huruhuru/src/main/java/com/huruhuru/huruhuru/controller/MemberController.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/dto/request/member/MemberAuthRequest.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/SecurityConfig.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/config/jwt/JwtTokenProvider.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/global/exception/GlobalExceptionHandler.java
  huruhuru/src/main/java/com/huruhuru/huruhuru/service/MemberService.java
Labels: fix
